config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  namespace 'api' do
    resources :checks, only: :create
  end

  scope module: :web do
    root 'home#show'

    post 'auth/:provider', to: 'auth#request', as: :auth_request
    get 'auth/:provider/callback', to: 'auth#callback', as: :callback_auth
    resources :auth, only: %i[new destroy]

    resources :repositories, only: %i[index show create new destroy] do
      scope module: :repositories do
        resources :checks, only: %i[show create]
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/repository.rb
# frozen_string_literal: true

class Repository < ApplicationRecord
  extend Enumerize
  belongs_to :user, class_name: 'User'
  has_many :checks, class_name: 'Repository::Check', dependent: :destroy
  validates :github_id, presence: true

  enumerize :language, in: %w[javascript ruby]
end

app/models/repository/check.rb
# frozen_string_literal: true

class Repository::Check < ApplicationRecord
  include AASM
  belongs_to :repository, class_name: 'Repository'

  aasm column: :aasm_state, whiny_transitions: false do
    state :created, initial: true
    state :checking
    state :finished
    state :failed

    event :check do
      transitions from: %i[created], to: :checking
    end

    event :finish do
      transitions from: %i[checking], to: :finished
    end

    event :fail do
      transitions from: :checking, to: :failed
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :repositories, dependent: :destroy

  def self.login_with_oauth(auth)
    user = find_or_initialize_by(email: auth.info.email)
    user.uid = auth.uid
    user.avatar = auth.info.image
    user.provider = auth.provider
    user.email = auth.info.email
    user.nickname = auth.info.name
    user.token = auth.credentials.token
    user
  end
end

app/controllers/api/application_controller.rb
# frozen_string_literal: true

class Api::ApplicationController < ApplicationController
  skip_before_action :verify_authenticity_token
end

app/controllers/api/checks_controller.rb
# frozen_string_literal: true

class Api::ChecksController < Api::ApplicationController
  def create
    repository = Repository.find_by(github_id: params['repository']['id'])
    return if repository.nil?

    check = repository.checks.new
    if check.save
      LintRepositoryJob.perform_later(check.id)
    end
    render json: { '200': 'OK' }, status: :ok
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include AuthConcern
  include Pundit::Authorization

  helper_method :current_user, :signed_in?

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    flash[:alert] = t('permission_denied')
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/concerns/add_webhook_stub.rb
# frozen_string_literal: true

class AddWebhookStub
  def initialize(*options); end

  def config
    self
  end

  def hooks(_)
    [self]
  end

  def url
    ''
  end

  def create_hook(*_args)
    'Hook was created.'
  end
end

app/controllers/concerns/application_container.rb
# frozen_string_literal: true

class ApplicationContainer
  extend Dry::Container::Mixin

  if Rails.env.test?
    register :add_webhook, -> { AddWebhookStub }
    register :load_repository, -> { LoadRepositoryStub }
    register :linter, -> { LinterStub }
  else
    register :add_webhook, -> { Octokit::Client }
    register :load_repository, -> { LoadRepository }
    register :linter, -> { Linter }
  end
end

app/controllers/concerns/auth_concern.rb
# frozen_string_literal: true

module AuthConcern
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def signed_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    return if signed_in?

    redirect_to(new_auth_path, notice: t('introduce_yourself'))
  end
end

app/controllers/concerns/authentication.rb
# frozen_string_literal: true

module Authentication
  def sign_in(user)
    session[:user_id] = user.id
  end

  def sign_out
    session.delete(:user_id)
    session.clear
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    return if signed_in?

    redirect_to(sign_in_path, notice: t('introduce_yourself_cowboy'))
  end

  def authenticate_admin!
    authorize :admin, :admin?
  end
end

app/controllers/concerns/load_repository.rb
# frozen_string_literal: true

class LoadRepository
  def self.download(link, id)
    `rm -rf "repositories/#{id}"`
    Git.clone(link, "repositories/#{id}")
  end
end

app/controllers/web/auth_controller.rb
# frozen_string_literal: true

class Web::AuthController < ApplicationController
  def callback
    auth = request.env['omniauth.auth']
    user = User.login_with_oauth(auth)
    if user.save
      sign_in(user)
      redirect_to root_path, notice: t('welcome', name: user.nickname)
    else
      redirect_to root_path, alert: t('auth_error')
    end
  end

  def new; end

  def destroy
    user = User.find(params[:id])
    sign_out
    redirect_to root_path, notice: t('see_you', name: user.nickname)
  end
end

app/controllers/web/home_controller.rb
# frozen_string_literal: true

class Web::HomeController < ApplicationController
  def show; end
end

app/controllers/web/repositories/application_controller.rb
# frozen_string_literal: true

class Web::Repositories::ApplicationController < ApplicationController
  before_action :authenticate_user!
end

app/controllers/web/repositories/checks_controller.rb
# frozen_string_literal: true

class Web::Repositories::ChecksController < Web::Repositories::ApplicationController
  def show
    @check = Repository::Check.find(params[:id])
    authorize @check

    @repository = @check.repository
    @result = @check.result
  end

  def create
    @repository = find_repository
    @check = @repository.checks.new
    authorize @check

    if @check.save
      LintRepositoryJob.perform_later(@check.id)
      redirect_to repository_path(@repository), notice: t('.success')
    else
      redirect_to repository_path(@repository), alert: t('.fail')
    end
  end

  private

  def find_repository
    @repository = Repository.find(params[:repository_id])
  end
end

app/controllers/web/repositories_controller.rb
# frozen_string_literal: true

class Web::RepositoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @repositories = current_user.repositories
  end

  def show
    @repository = Repository.find(params[:id])
    authorize @repository

    @checks = @repository.checks.order(created_at: :desc)
    @check = @repository.checks.build
  end

  def new
    @repository = Repository.new
    @repos = Rails.cache.fetch("repository_form_#{current_user.nickname}", expires_in: 1.day) do
      client = ApplicationContainer[:octokit].new access_token: current_user.token, per_page: 100
      client.repos.delete_if { |r| Repository.language.values.exclude?(r['language']&.downcase) }
    end
  end

  def create
    @repository = current_user.repositories.new(repository_params)
    if @repository.save
      LoadRepositoryInfoJob.perform_later(@repository.id)
      redirect_to repository_path(@repository), notice: t('.success')
    else
      flash[:alert] = @repository.errors.first.full_message
      redirect_to new_repository_path
    end
  end

  def destroy
    @repository = Repository.find(params[:id])
    authorize @repository

    if @repository.destroy
      redirect_to repositories_path, alert: t('.success')
    else
      redirect_to repositories_path, alert: t('.fail')
    end
  end

  private

  def repository_params
    params.require(:repository).permit([:github_id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def flash_class(type)
    case type
    when 'error', 'alert'
      'alert-secondary'
    when 'notice', 'success'
      'alert-light'
    else
      type.to_s
    end
  end

  def passed_theme(bull)
    bull ? 'text-success' : 'text-danger'
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = t('app_name')
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/shared/nav'
    .container
      = render 'layouts/shared/flash'
      = yield

app/views/layouts/shared/_flash.html.slim
- if flash.any?
  .container.my-2
    - flash.each do |type, msg|
      div class="alert shadow alert-dismissible #{flash_class(type.to_s)}"
        = msg
        button type='button' class='btn-close' data-bs-dismiss='alert' aria-label='Close'

app/views/layouts/shared/_nav.html.slim
nav.navbar.navbar-expand-lg.px-3.mb-3.rounded-bottom.border-bottom.shadow-lg.border-1.sticky-top.bg-light
  .container-fluid
    = link_to t('github_quality'), root_path, class: 'navbar-brand text-black'

  .navbar-nav.me-auto.mb-2.mb-lg-0

  - if signed_in?
    .nav-item
      = link_to t('repositories'), repositories_path, class: 'nav-link text-secondary'

  .nav-item.dropdown
    a#navbarDropdown.nav-link.dropdown-toggle.text-secondary[href='#' role='button' data-bs-toggle='dropdown' aria-expanded='false']
      - if signed_in? && current_user.avatar.present?
        = current_user.nickname
        = image_tag current_user.avatar, size: '32x32', class: 'rounded-3 ms-2'
      - else
        i.fa-solid.fa-right-to-bracket

    .dropdown-menu-end.dropdown-menu[aria-labelledby="navbarDropdown"]
      - if signed_in?
        li
          = link_to t('sign_out'), auth_path(current_user.id), method: :delete, class: 'dropdown-item text-secondary'
      - else
        li
          = link_to t('sign_in'), new_auth_path, class: 'dropdown-item text-secondary'

app/views/web/home/show.html.slim
h4
  = t('home_page')

app/views/web/repositories/checks/show.html.slim
  h2
    b = link_to @repository.name, @repository.link
  h4.mt-3
    = t('state')
    b = @check.aasm.human_state
    br
    = t('check_passed')
    b = @check.passed
    br
    = t('created_at')
    b = @check.created_at
  br
  = link_to t('back'), repository_path(@repository), class: 'btn btn-outline-dark'

  - if @check.finished?
    .my-3
      - if @check.commit.present?
        = t('commit')
        = link_to @check.commit[(-10..-1)], @check.commit

  - if @result.present?
      div class="d-flex justify-content-between mt-3 #{passed_theme(@check.passed?)}"
        span
          = t('problems_file_count')
          b = @result['problems_file_count']
        span
          = t('offense_count')
          b = @result['offense_count']
  hr
    b.row
      .col-6
        = t('message')
      .col-4
        = t('rule')
      .col-2
        = t('line_column')
  - if @result.present?
    .list-group
      - @result['files'].each do |f|
        b.mt-3.mb-1
          = f['path']
        br
        - f['messages'].each do |of|
          .list-group-item.list-group-item-secondary.list-group-item-action
            .row
              .col-6
                = of['message']
              .col-4
                = of['rule']
              .col-2
                = of['line_column']

app/views/web/repositories/index.html.slim
h1
  = t('my_repos')
  = link_to t('new_repo'), new_repository_path, class: 'btn btn-outline-dark m-3'
.row
  - @repositories.each do |rep|
    .card.my-3.col-6
      .card-body.shadow
        = link_to repository_path(rep), class: 'text-dark text-decoration-none' do
          h2.card-title.mb-3
            = rep.name
        .card-footer
          br
          .d-flex.justify-content-end
            = link_to t('destroy'), repository_path(rep), method: :delete, data: { confirm: t('confirm_destroy') }, class: 'btn btn-sm btn-outline-dark'

app/views/web/repositories/new.html.slim
= simple_form_for @repository do |f|
  = f.input :github_id, collection: @repos, label_method: :name, value_method: :id
  = f.button :submit, class: 'btn btn-outline-dark my-3'

small
  i = t('description_new')

app/views/web/repositories/show.html.slim
h1
  .my-3
    b
      = @repository.name

p
  .my-3
    = link_to @repository.link, @repository.link if @repository.link.present?
  .my-3
    = t('language')
    b
      = @repository.language

  = link_to t('new_check'), repository_checks_path(@repository, @check), method: :post, class: 'btn btn-dark'

h2.my-3
  = t('checks')
.d-flex.justify-content-between.mb-3
  .col-2
    = t('state')
  .col-2
    = t('check_passed')
  .col-2
    = t('commit')
  .col-6
    = t('created_at')
.list-group
  - @checks.each do |check|
    - if check.id.present?
      = link_to repository_check_path(check.repository, check), class: 'text-decoration-none' do
        .d-flex.justify-content-between.list-group-item.list-group-item-action.list-group-item-dark.rounded-3
          .col-2
            = check.aasm_state
          .col-2
            = check.passed
          .col-2.text-primary
            = check.commit[(-10..-1)] if check.commit
          .col-6
            = check.created_at